version: "2"

linters:
  enable:
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
    - path: mock/
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
